### ISSUE TITLE
Nest.js doesn't boot up, fix for mongodb config needed

### ISSUE THREAD

**Issue by ghost** [Norbert-Waszkowiak-WAT/ppz-yapmasters#1]
Po włączeniu MongoDB w dockerze oraz `npm run start` w terminalu, niestety konfiguracja nie jest według nest.js odpowiednia.

```
[12:46:11] Starting compilation in watch mode...

[12:46:15] Found 0 errors. Watching for file changes.

[Nest] 93675  - 13.10.2024, 12:46:15     LOG [NestFactory] Starting Nest application...
[Nest] 93675  - 13.10.2024, 12:46:16     LOG [InstanceLoader] MongooseModule dependencies initialized +41ms
[Nest] 93675  - 13.10.2024, 12:46:16     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
[Nest] 93675  - 13.10.2024, 12:46:16     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 93675  - 13.10.2024, 12:46:16     LOG [InstanceLoader] MongooseCoreModule dependencies initialized +12ms
[Nest] 93675  - 13.10.2024, 12:46:16   ERROR [ExceptionHandler] The 2nd parameter to `mongoose.model()` should be a schema or a POJO
Error: The 2nd parameter to `mongoose.model()` should be a schema or a POJO
    at Connection.model (/home/mrroboto/Applications/ppz-yapmasters/backend/node_modules/mongoose/lib/connection.js:1184:11)
    at InstanceWrapper.useFactory [as metatype] (/home/mrroboto/Applications/ppz-yapmasters/backend/node_modules/@nestjs/mongoose/dist/mongoose.providers.js:16:108)
    at Injector.instantiateClass (/home/mrroboto/Applications/ppz-yapmasters/backend/node_modules/@nestjs/core/injector/injector.js:368:55)
    at callback (/home/mrroboto/Applications/ppz-yapmasters/backend/node_modules/@nestjs/core/injector/injector.js:65:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Injector.resolveConstructorParams (/home/mrroboto/Applications/ppz-yapmasters/backend/node_modules/@nestjs/core/injector/injector.js:144:24)
    at async Injector.loadInstance (/home/mrroboto/Applications/ppz-yapmasters/backend/node_modules/@nestjs/core/injector/injector.js:70:13)
    at async Injector.loadProvider (/home/mrroboto/Applications/ppz-yapmasters/backend/node_modules/@nestjs/core/injector/injector.js:97:9)
    at async Injector.lookupComponentInImports (/home/mrroboto/Applications/ppz-yapmasters/backend/node_modules/@nestjs/core/injector/injector.js:289:17)
    at async Injector.lookupComponentInParentModules (/home/mrroboto/Applications/ppz-yapmasters/backend/node_modules/@nestjs/core/injector/injector.js:252:33)
```

**Comment by LonleySailor** [comment]
Naprawione. Błąd dotyczył nieprawidłowego nazewnictwa w export w user.schema.ts
